{% set name = "pandas-profiling" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8897c2628e3a9b5c915d038aa1782be7fa9e322e405a51aa4586466ab84e8461

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy >=1.4.1
    - requests >=2.24.0
    - pydantic >=1.8.1
    - pyyaml >=5.0.0
    - missingno >=0.4.2
    - pandas >=0.25.3,!=1.0.1,!=1.0.0,!=1.0.2,!=1.1.0
    - matplotlib-base >=3.2.0
    - jinja2 >=2.11.1
    - htmlmin >=0.1.12
    - phik >=0.11.1
    - visions 0.7.4
    - numpy >=1.16.0
    - tangled-up-in-unicode 0.2.0
    - tqdm >=4.48.2
    - imagehash
    - pillow
    - seaborn-base >=0.10.1
    - joblib 1.1.0
    - markupsafe 2.1.1
    - multimethod >=1.4

test:
  imports:
    - pandas_profiling
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/pandas-profiling/pandas-profiling
  license: MIT
  license_file: LICENSE
  summary: Generate profile report for pandas DataFrame
  dev_url: http://github.com/pandas-profiling/pandas-profiling
  doc_url: https://pandas-profiling.github.io/pandas-profiling/docs/

extra:
  recipe-maintainers:
    - sbrugman
    - proinsias
    - philip-khor
